### ISSUE TITLE
Calculation of probabilities

### ISSUE THREAD

**Issue by Anand270294** [yingmao/Quantum-Generative-Adversarial-Network#2]
Hi, I would like to know why is the probabilities calculated in such a manner:
`def get_probabilities(circ,counts=1000):
    job = execute(circ, backend, shots=counts)
    results = job.result().get_counts(circ)
    try:
        prob = results['0']/(results['1']+results['0'])
        prob = (prob-0.5)
        if prob <= 0.005:
            prob = 0.005
        else:
            prob = prob*2
    except:
        prob = 1
    return prob`
Why is there a need to minus 0.5 from the measured probabilites and then multiply it by 2?

**Comment by Samuelstein1224** [comment]
When measuring, you are observing the following amplitude:

0.5+0.5|<Phi,Psi>|^2

**Comment by Anand270294** [comment]
Understood, thanks for the help!
